Update Tangokoto.txt
SDLYYZ/Tangokoto pull request #20
Opened 2023-10-21 06:58 UTC by ZhngJaH

2023-10-29 01:14 UTC, CornWorld commented
@ZhngJaH ？

2023-10-29 01:20 UTC, CornWorld requested changes
这啥啊 QwQ

2023-10-29 03:10 UTC, orangeZSCB commented
> 这啥啊 QwQ @ZhngJaH

![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/c895c152-2905-4b9b-a4dd-2b8c473ae710)
![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/8ff8cc3f-60af-4411-81a5-7cb65abe1349)
![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/19337367-ba9f-4a84-9b66-406e7e8d25d3)
![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/f7f7ff2a-7ed1-4349-adc4-9380b97d622c)
![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/fab4d3f8-c082-43ab-a513-cc3fa95048a5)

XSWL

一些事情：
![image](https://github.com/SDLYYZ/Tangokoto/assets/90908765/164d9bda-bc2e-4e00-aa9d-c9ba253ff418)

2023-10-30 09:14 UTC, CornWorld commented
@orangeZSCB @ZhngJaH 此处建议加入更多背景介绍，单看这一句很难看明白。

2023-10-30 11:28 UTC, orangeZSCB commented
> @orangeZSCB @ZhngJaH 此处建议加入更多背景介绍，单看这一句很难看明白。

just add some texts, like this:（23/10/13唐老师写于2023B小组，“道”并非错别字）

2023-10-30 12:41 UTC, merged