updated tangokoto python version
SDLYYZ/Tangokoto pull request #26
Opened 2023-12-31 13:55 UTC by orangeZSCB

As you can see...

2024-01-01 12:12 UTC, qwqVictor requested changes
重构代码应当保持和原有代码的行为一致，具体需要修改之处在 Review 报告中有所体现。感谢 PR。

2024-01-01 12:12 UTC, qwqVictor commented on src_py/tgkt.py
> +    index = min(max(index, 0), length - 1)  # Ensure index is within range
原有 API 实现中，ID 非法则随机返回 1 条。重构后的行为应当保持一致。此处可考虑修改为
```python
index = randid if index < 0 or index >= length else index
```

2024-01-01 12:12 UTC, qwqVictor commented on src_py/tgkt.py
> +        js_output = f"function doTangokoto(){{document.write(\"<span class='hitokoto' title='Tangokoto'>{output_raw}</span>\");}}"
原 API 实现中对 JSONP 和 JavaScript 输出进行了 `htmlspecialchars` 过滤来预防可能存在的 XSS 攻击，重构实现中应保持行为一致。

考虑使用：
```python
def htmlspecialchars(text): 
    return (
      text.replace("&", "&amp;"). 
      replace('"', "&quot;"). 
      replace("<", "&lt;"). 
      replace(">", "&gt;") 
    )
```

2024-01-01 12:12 UTC, qwqVictor commented on src_py/tgkt.py
> +@app.route('/pytangokoto', methods=['GET'])
API 路径建议尽量保持行为一致。

2024-01-01 12:12 UTC, qwqVictor commented on src_py/tgkt.py
> +with open("/home/orange/TangokotoAPI/Tangokoto.txt", "r", encoding="utf-8") as file: # please change the folder!!!!!!
可以考虑设置为相对路径或使用参数传入的形式。避免用户手动修改代码从而不利于升级。

2024-01-05 13:23 UTC, orangeZSCB commented on src_py/tgkt.py
> +@app.route('/pytangokoto', methods=['GET'])
change path to `/tangokoto` ?

2024-01-05 13:33 UTC, qwqVictor commented on src_py/tgkt.py
> +@app.route('/pytangokoto', methods=['GET'])
> change path to `/tangokoto` ?

reasonable

2024-01-05 13:48 UTC, orangeZSCB commented
改了一哈子，现在怎么样？

2024-01-05 13:50 UTC, orangeZSCB commented
holy crap wait me a min

2024-01-05 13:57 UTC, orangeZSCB commented
alright check now

2024-01-05 15:29 UTC, qwqVictor approved these changes

2024-01-05 15:30 UTC, qwqVictor commented
我抽空本地测试一下 API 行为，行为没有问题就可以 merge 了，若有时间建议编写 Dockerfile、部署文档等

2024-01-20 04:55 UTC, orangeZSCB commented
运作的怎么样？
我把Dockerfile和文档给咕咕咕了（（（

2024-07-08 09:31 UTC, merged